# Generated by Django 2.2.5 on 2019-09-30 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='time_left',
            field=models.TimeField(default=datetime.time(0, 20)),
        ),
    ]
