version: '3.1'

services:
  queue:
    image: redis
    ports:
      - 6379:6379
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "behind"
    volumes:
      - ./var/mysql:/var/lib/mysql
  behind-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/src
    ports:
      - 8000:8000
    depends_on:
      - db
      - queue

