version: '3.1'

services:
  queue:
    restart: always
    image: redis
    ports:
      - 6379:6379
  behind-api:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.production
    ports:
      - 80:8000
      - 9001:9001
    depends_on:
      - queue
