version: '3.1'

services:
  queue:
    image: redis
    ports:
      - 6379:6379
  behind-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8000
    depends_on:
      - queue
