# Generated by Django 2.2.6 on 2019-10-07 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transaction_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transaction_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomings', to=settings.AUTH_USER_MODEL),
        ),
    ]
