# Generated by Django 2.2.6 on 2019-10-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20191007_0427'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='purchase',
            table='purchases',
        ),
    ]
