# Generated by Django 2.2.6 on 2019-10-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.PositiveIntegerField()),
                ('device_type', models.PositiveSmallIntegerField(choices=[(1, 'ios'), (2, 'android'), (3, 'web')])),
                ('release_state', models.PositiveSmallIntegerField(choices=[(1, 'released'), (2, 'in_review'), (3, 'rejected')], default=2)),
                ('update_state', models.PositiveSmallIntegerField(choices=[(1, 'no_alert'), (2, 'alert'), (2, 'force_alert')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_versions',
            },
        ),
    ]
