# Generated by Django 2.2.6 on 2019-10-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_appversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='update_state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'no_alert'), (2, 'alert'), (3, 'force_alert')], default=1),
        ),
    ]
