# Generated by Django 2.2.5 on 2019-09-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_userjobhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobhistory',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='userjobhistory',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.Job'),
        ),
    ]
