# Generated by Django 2.2.5 on 2019-09-15 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
