# Generated by Django 2.2.5 on 2019-09-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='introduction',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_seeker_intro',
            field=models.TextField(blank=True),
        ),
    ]
