# Generated by Django 2.2.5 on 2019-09-10 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190910_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobhistory',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='job_histories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
