# Generated by Django 2.2.6 on 2019-10-12 12:16

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pg_response',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
